---
id: rubykaigi2017-frozen_string_literal
base_name: rubykaigi2017-frozen_string_literal
tags:
- ruby
presentation_date: 2017/09/19
version: 2017.09.19
licenses: []
slideshare_id: how-to-specify-frozenstringliteral-true
speaker_deck_id: how-to-specify-frozen-string-literal-true
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
